#!/usr/bin/env bash
set -Eeuo pipefail

onErr() {
  local rc=$?
  echo "[ERROR] rc=${rc} line=${BASH_LINENO[0]} cmd=${BASH_COMMAND}" >&2
}
onExit() {
  local rc=$?
  echo "[EXIT] rc=${rc}" >&2
}
trap onErr ERR
trap onExit EXIT

requireCmd() {
  local cmd="$1"
  command -v "$cmd" >/dev/null 2>&1 || {
    echo "ERROR: missing command: $cmd" >&2
    exit 127
  }
}

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Auto-load baseline connection env generated by start_baseline.sh
BASELINE_ENV_FILE="${ROOT}/services/baseline.env"
if [[ -f "$BASELINE_ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$BASELINE_ENV_FILE"
fi

SIFT100K_DIR="${SIFT100K_DIR:-$ROOT/datasets/custom/sift100k}"
SIFT1M_DIR="${SIFT1M_DIR:-$ROOT/datasets/custom/sift1M}"
SIFT10M_DIR="${SIFT10M_DIR:-$ROOT/datasets/custom/sift10M}"

OUT_YML="${OUT_YML:-$ROOT/bench_runs/bench_custom_sift_build_then_query.yml}"

MILVUS_URI="${MILVUS_URI:-http://localhost:19530}"
MILVUS_PASSWORD="${MILVUS_PASSWORD:-}"

QDRANT_URL="${QDRANT_URL:-http://localhost:6333}"

WEAVIATE_URL="${WEAVIATE_URL:-http://localhost:8080}"
WEAVIATE_NO_AUTH="${WEAVIATE_NO_AUTH:-true}"
WEAVIATE_API_KEY="${WEAVIATE_API_KEY:-}"

PGVECTOR_HOST="${PGVECTOR_HOST:-localhost}"
PGVECTOR_PORT="${PGVECTOR_PORT:-5432}"
PGVECTOR_DB_NAME="${PGVECTOR_DB_NAME:-vectordb}"
PGVECTOR_USER_NAME="${PGVECTOR_USER_NAME:-postgres}"
PGVECTOR_PASSWORD="${PGVECTOR_PASSWORD:-}"

ELASTIC_CLOUD_ID="${ELASTIC_CLOUD_ID:-}"
ELASTIC_PASSWORD="${ELASTIC_PASSWORD:-}"
ELASTIC_NUM_CANDIDATES="${ELASTIC_NUM_CANDIDATES:-100}"
ELASTIC_NUMBER_OF_SHARDS="${ELASTIC_NUMBER_OF_SHARDS:-1}"
ELASTIC_NUMBER_OF_REPLICAS="${ELASTIC_NUMBER_OF_REPLICAS:-0}"

ELASTICSEARCH_SCHEME="${ELASTICSEARCH_SCHEME:-http}"
ELASTICSEARCH_HOST="${ELASTICSEARCH_HOST:-localhost}"
ELASTICSEARCH_PORT="${ELASTICSEARCH_PORT:-9200}"
ELASTICSEARCH_USER="${ELASTICSEARCH_USER:-elastic}"
ELASTICSEARCH_PASSWORD="${ELASTICSEARCH_PASSWORD:-elastic}"

PINECONE_API_KEY="${PINECONE_API_KEY:-}"
PINECONE_INDEX_NAME="${PINECONE_INDEX_NAME:-vdbbench-sift}"

DOCKER_VOLUME_DIRECTORY="${DOCKER_VOLUME_DIRECTORY:-/var/tmp}"

LSMVEC_DB_ROOT_100K="${LSMVEC_DB_ROOT_100K:-$DOCKER_VOLUME_DIRECTORY/lsmvec/sift100k}"
LSMVEC_DB_ROOT_1M="${LSMVEC_DB_ROOT_1M:-$DOCKER_VOLUME_DIRECTORY/lsmvec/sift1m}"
LSMVEC_DB_ROOT_10M="${LSMVEC_DB_ROOT_10M:-$DOCKER_VOLUME_DIRECTORY/lsmvec/sift10m}"

K="${K:-10}"
NUM_CONCURRENCY="${NUM_CONCURRENCY:-1}"

HNSW_M="${HNSW_M:-32}"
HNSW_EF_CONSTRUCTION="${HNSW_EF_CONSTRUCTION:-200}"
MILVUS_EF_SEARCH="${MILVUS_EF_SEARCH:-50}"
WEAVIATE_EF="${WEAVIATE_EF:-10}"
QDRANT_EF_CONSTRUCT="${QDRANT_EF_CONSTRUCT:-200}"

REPEATS="${REPEATS:-1}"

ENABLE_DOCKER_MEM_SAMPLING="${ENABLE_DOCKER_MEM_SAMPLING:-true}"
DOCKER_STATS_INTERVAL_SEC="${DOCKER_STATS_INTERVAL_SEC:-1}"
DOCKER_STATS_OUT_DIR="${DOCKER_STATS_OUT_DIR:-$ROOT/bench_runs/docker_stats}"
DOCKER_STATS_PROJECTS="${DOCKER_STATS_PROJECTS:-milvus,weaviate}"
DOCKER_STATS_NAME_FILTERS="${DOCKER_STATS_NAME_FILTERS:-qdrant,pgvector,elasticsearch}"

ENABLE_HOST_MEM_SAMPLING="${ENABLE_HOST_MEM_SAMPLING:-true}"
HOST_STATS_INTERVAL_SEC="${HOST_STATS_INTERVAL_SEC:-1}"
HOST_STATS_OUT_DIR="${HOST_STATS_OUT_DIR:-$ROOT/bench_runs/host_stats}"

TARGET_RAW="${1:-all}"
DATASETS_RAW="${2:-${SIFT_DATASETS:-100k,1m}}"

TARGET=""

normalizeTarget() {
  local t="$1"
  case "$t" in
    all|baselines|lsmvec|milvushnsw|qdrantlocal|weaviate|pgvectorhnsw|elasticsearch|elasticcloudhnsw|pinecone) echo "$t" ;;
    milvus) echo "milvushnsw" ;;
    qdrant) echo "qdrantlocal" ;;
    pgvector) echo "pgvectorhnsw" ;;
    elastic|elasticsearch) echo "elasticsearch" ;;
    elasticcloud) echo "elasticcloudhnsw" ;;
    *)
      echo ""
      ;;
  esac
}

TARGET="$(normalizeTarget "$TARGET_RAW")"

wantSection() {
  local section="$1" # milvushnsw|qdrantlocal|weaviate|pgvectorhnsw|elasticsearch|elasticcloudhnsw|pinecone|lsmvec
  case "$TARGET" in
    all) return 0 ;;
    baselines)
      [[ "$section" != "lsmvec" ]]
      return $?
      ;;
    *)
      [[ "$section" == "$TARGET" ]]
      return $?
      ;;
  esac
}

# datasets parsing, supports: 100k,1m,10m,all
DATASETS_NORM="${DATASETS_RAW,,}"
DATASETS_NORM="${DATASETS_NORM//[[:space:]]/}"
DATASETS_NORM=",$DATASETS_NORM,"

WANT_100K=false
WANT_1M=false
WANT_10M=false

if [[ "$DATASETS_NORM" == *",all,"* ]]; then
  WANT_100K=true
  WANT_1M=true
  WANT_10M=true
else
  [[ "$DATASETS_NORM" == *",100k,"* ]] && WANT_100K=true
  [[ "$DATASETS_NORM" == *",1m,"* ]] && WANT_1M=true
  [[ "$DATASETS_NORM" == *",10m,"* ]] && WANT_10M=true
fi

if [[ "$WANT_100K" != "true" && "$WANT_1M" != "true" && "$WANT_10M" != "true" ]]; then
  echo "ERROR: no datasets selected. Use 100k,1m,10m or all" >&2
  exit 1
fi

DATASETS_TAG="${DATASETS_NORM#,}"
DATASETS_TAG="${DATASETS_TAG%,}"
DATASETS_TAG="${DATASETS_TAG//,/__}"

verifyDatasetDir() {
  local dir="$1"
  if [[ ! -d "$dir" ]]; then
    echo "ERROR: dataset dir not found: $dir" >&2
    exit 1
  fi

  if [[ ! -f "$dir/train.parquet" ]]; then
    shopt -s nullglob
    local shards=("$dir"/train-*-of-*.parquet)
    shopt -u nullglob
    if [[ ${#shards[@]} -eq 0 ]]; then
      echo "ERROR: missing train.parquet or train-*-of-*.parquet in $dir" >&2
      exit 1
    fi
  fi

  [[ -f "$dir/test.parquet" ]] || { echo "ERROR: missing test.parquet in $dir" >&2; exit 1; }
  [[ -f "$dir/neighbors.parquet" ]] || { echo "ERROR: missing neighbors.parquet in $dir" >&2; exit 1; }
}

trainFileCount() {
  local dir="$1"
  if [[ -f "$dir/train.parquet" ]]; then
    echo 1
    return
  fi
  shopt -s nullglob
  local shards=("$dir"/train-*-of-*.parquet)
  shopt -u nullglob
  echo "${#shards[@]}"
}

getServerMemSummaryMiB() {
  awk '
    $1=="MemTotal:" {t=$2}
    $1=="MemAvailable:" {a=$2}
    END {
      if (t=="" || a=="") {
        printf "0.00\t0.00\t0.00\n"
        exit
      }
      used_kib = t - a
      printf "%.2f\t%.2f\t%.2f\n", used_kib/1024.0, t/1024.0, a/1024.0
    }
  ' /proc/meminfo 2>/dev/null || echo -e "0.00\t0.00\t0.00"
}

printSystemMemBefore() {
  local label="$1"
  local used total avail
  IFS=$'\t' read -r used total avail < <(getServerMemSummaryMiB)
  echo "system memory before running ${label} is ${used} MiB (used), total ${total} MiB, available ${avail} MiB"
}

ensureElasticsearchReachable() {
  local configuredScheme="${ELASTICSEARCH_SCHEME}"
  local configuredHost="${ELASTICSEARCH_HOST}"
  local configuredPort="${ELASTICSEARCH_PORT}"
  local retries="${ELASTICSEARCH_READY_RETRIES:-30}"

  local hosts=()
  local ports=()
  local schemes=()
  local host="" port="" scheme=""
  local attempted=""
  local dockerHintShown="false"

  appendUnique() {
    local value="$1"
    shift
    local -n arr="$1"
    local existing=""

    [[ -n "$value" ]] || return 0
    for existing in "${arr[@]}"; do
      [[ "$existing" == "$value" ]] && return 0
    done
    arr+=("$value")
  }

  tryUrl() {
    local url="$1"
    # Try with explicit auth first (for secured nodes), then without auth.
    curl -s -o /dev/null -m 3 -u "${ELASTICSEARCH_USER}:${ELASTICSEARCH_PASSWORD}" "$url" 2>/dev/null       || curl -s -o /dev/null -m 3 "$url" 2>/dev/null
  }

  appendUnique "$configuredHost" hosts
  appendUnique "$configuredPort" ports
  appendUnique "$configuredScheme" schemes

  if [[ "$configuredHost" == "localhost" ]]; then
    appendUnique "127.0.0.1" hosts
    appendUnique "host.docker.internal" hosts

    if command -v ip >/dev/null 2>&1; then
      appendUnique "$(ip route 2>/dev/null | awk '/^default/ {print $3; exit}')" hosts
    fi

    appendUnique "172.17.0.1" hosts
  fi

  # If an elasticsearch container exists, include its published host port for 9200/tcp.
  if command -v docker >/dev/null 2>&1     && docker ps -a --format '{{.Names}}' | grep -Fxq 'elasticsearch'; then
    local mappedPort=""
    mappedPort="$(docker port elasticsearch 9200/tcp 2>/dev/null | awk -F: 'NR==1 {print $NF}')"
    appendUnique "$mappedPort" ports
  fi

  if [[ "$configuredScheme" == "http" ]]; then
    appendUnique "https" schemes
  elif [[ "$configuredScheme" == "https" ]]; then
    appendUnique "http" schemes
  fi

  for scheme in "${schemes[@]}"; do
    for host in "${hosts[@]}"; do
      for port in "${ports[@]}"; do
        local url="${scheme}://${host}:${port}/"
        attempted+=" ${url}"

        for _ in $(seq 1 "$retries"); do
          if tryUrl "$url"; then
            if [[ "$host" != "$configuredHost" ]]; then
              echo "[INFO] Elasticsearch is reachable via ${host}; overriding ELASTICSEARCH_HOST for this run."
              ELASTICSEARCH_HOST="$host"
            fi
            if [[ "$port" != "$configuredPort" ]]; then
              echo "[INFO] Elasticsearch is reachable via port ${port}; overriding ELASTICSEARCH_PORT for this run."
              ELASTICSEARCH_PORT="$port"
            fi
            if [[ "$scheme" != "$configuredScheme" ]]; then
              echo "[INFO] Elasticsearch is reachable via scheme ${scheme}; overriding ELASTICSEARCH_SCHEME for this run."
              ELASTICSEARCH_SCHEME="$scheme"
            fi
            return 0
          fi
          sleep 1
        done
      done
    done
  done

  echo "ERROR: Elasticsearch is unreachable at ${configuredScheme}://${configuredHost}:${configuredPort}/ after ${retries}s per endpoint candidate" >&2
  echo "Hint: attempted endpoints:${attempted}" >&2
  echo "Hint: start baseline services first (e.g. ./start_baseline.sh elasticsearch)." >&2
  echo "Hint: if your node uses TLS, set ELASTICSEARCH_SCHEME=https." >&2
  if command -v docker >/dev/null 2>&1     && docker ps -a --format '{{.Names}}' | grep -Fxq 'elasticsearch'; then
    echo "Hint: an 'elasticsearch' container exists; check readiness with: docker logs --tail 100 elasticsearch" >&2
    echo "Hint: inspect mapped ports with: docker port elasticsearch 9200/tcp" >&2
    dockerHintShown="true"
  fi
  if [[ "$configuredHost" == "localhost" && "$dockerHintShown" != "true" ]]; then
    echo "Hint: in containers/devcontainers, set ELASTICSEARCH_HOST and ELASTICSEARCH_PORT to the Docker host endpoint." >&2
  fi
  exit 1
}

writeYaml() {
  local sift100kCount="" sift1mCount="" sift10mCount=""

  [[ "$WANT_100K" == "true" ]] && sift100kCount="$(trainFileCount "$SIFT100K_DIR")"
  [[ "$WANT_1M" == "true" ]] && sift1mCount="$(trainFileCount "$SIFT1M_DIR")"
  [[ "$WANT_10M" == "true" ]] && sift10mCount="$(trainFileCount "$SIFT10M_DIR")"

  mkdir -p "$(dirname "$OUT_YML")"

  cat > "$OUT_YML" <<YML
# Auto-generated. Do not edit by hand.
YML

  if wantSection "milvushnsw"; then
    cat >> "$OUT_YML" <<YML

milvushnsw:
YML
    if [[ "$WANT_100K" == "true" ]]; then
      cat >> "$OUT_YML" <<YML
  - db_label: milvus_sift100k
    uri: "$MILVUS_URI"
    password: "$MILVUS_PASSWORD"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D100K
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT100K_DIR"
    custom_dataset_size: 100000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift100kCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    m: $HNSW_M
    ef_construction: $HNSW_EF_CONSTRUCTION
    ef_search: $MILVUS_EF_SEARCH
    drop_old: true
    load: true
YML
    fi

    if [[ "$WANT_1M" == "true" ]]; then
      cat >> "$OUT_YML" <<YML

  - db_label: milvus_sift1m
    uri: "$MILVUS_URI"
    password: "$MILVUS_PASSWORD"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D1M
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT1M_DIR"
    custom_dataset_size: 1000000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift1mCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    m: $HNSW_M
    ef_construction: $HNSW_EF_CONSTRUCTION
    ef_search: $MILVUS_EF_SEARCH
    drop_old: true
    load: true
YML
    fi

    if [[ "$WANT_10M" == "true" ]]; then
      cat >> "$OUT_YML" <<YML

  - db_label: milvus_sift10m
    uri: "$MILVUS_URI"
    password: "$MILVUS_PASSWORD"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D10M
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT10M_DIR"
    custom_dataset_size: 10000000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift10mCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    m: $HNSW_M
    ef_construction: $HNSW_EF_CONSTRUCTION
    ef_search: $MILVUS_EF_SEARCH
    drop_old: true
    load: true
YML
    fi
  fi

  if wantSection "qdrantlocal"; then
    cat >> "$OUT_YML" <<YML

qdrantlocal:
YML
    if [[ "$WANT_100K" == "true" ]]; then
      cat >> "$OUT_YML" <<YML
  - db_label: qdrant_sift100k
    url: "$QDRANT_URL"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D100K
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT100K_DIR"
    custom_dataset_size: 100000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift100kCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    m: $HNSW_M
    ef_construct: $QDRANT_EF_CONSTRUCT
    drop_old: true
    load: true
YML
    fi

    if [[ "$WANT_1M" == "true" ]]; then
      cat >> "$OUT_YML" <<YML

  - db_label: qdrant_sift1m
    url: "$QDRANT_URL"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D1M
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT1M_DIR"
    custom_dataset_size: 1000000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift1mCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    m: $HNSW_M
    ef_construct: $QDRANT_EF_CONSTRUCT
    drop_old: true
    load: true
YML
    fi

    if [[ "$WANT_10M" == "true" ]]; then
      cat >> "$OUT_YML" <<YML

  - db_label: qdrant_sift10m
    url: "$QDRANT_URL"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D10M
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT10M_DIR"
    custom_dataset_size: 10000000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift10mCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    m: $HNSW_M
    ef_construct: $QDRANT_EF_CONSTRUCT
    drop_old: true
    load: true
YML
    fi
  fi

  if wantSection "weaviate"; then
    cat >> "$OUT_YML" <<YML

weaviate:
YML
    if [[ "$WANT_100K" == "true" ]]; then
      cat >> "$OUT_YML" <<YML
  - db_label: weaviate_sift100k
    url: "$WEAVIATE_URL"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D100K
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT100K_DIR"
    custom_dataset_size: 100000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift100kCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    m: $HNSW_M
    ef_construction: $HNSW_EF_CONSTRUCTION
    ef: $WEAVIATE_EF
    drop_old: true
    load: true
    no_auth: $WEAVIATE_NO_AUTH
YML
    fi

    if [[ "$WANT_1M" == "true" ]]; then
      cat >> "$OUT_YML" <<YML

  - db_label: weaviate_sift1m
    url: "$WEAVIATE_URL"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D1M
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT1M_DIR"
    custom_dataset_size: 1000000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift1mCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    m: $HNSW_M
    ef_construction: $HNSW_EF_CONSTRUCTION
    ef: $WEAVIATE_EF
    drop_old: true
    load: true
    no_auth: $WEAVIATE_NO_AUTH
YML
    fi

    if [[ "$WANT_10M" == "true" ]]; then
      cat >> "$OUT_YML" <<YML

  - db_label: weaviate_sift10m
    url: "$WEAVIATE_URL"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D10M
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT10M_DIR"
    custom_dataset_size: 10000000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift10mCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    m: $HNSW_M
    ef_construction: $HNSW_EF_CONSTRUCTION
    ef: $WEAVIATE_EF
    drop_old: true
    load: true
    no_auth: $WEAVIATE_NO_AUTH
YML
    fi
  fi

  if wantSection "pgvectorhnsw"; then
    cat >> "$OUT_YML" <<YML

pgvectorhnsw:
YML
    if [[ "$WANT_100K" == "true" ]]; then
      cat >> "$OUT_YML" <<YML
  - db_label: pgvector_sift100k
    host: "$PGVECTOR_HOST"
    port: $PGVECTOR_PORT
    db_name: "$PGVECTOR_DB_NAME"
    user_name: "$PGVECTOR_USER_NAME"
    password: "$PGVECTOR_PASSWORD"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D100K
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT100K_DIR"
    custom_dataset_size: 100000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift100kCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    m: $HNSW_M
    ef_construction: $HNSW_EF_CONSTRUCTION
    ef_search: $MILVUS_EF_SEARCH
    drop_old: true
    load: true
YML
    fi

    if [[ "$WANT_1M" == "true" ]]; then
      cat >> "$OUT_YML" <<YML

  - db_label: pgvector_sift1m
    host: "$PGVECTOR_HOST"
    port: $PGVECTOR_PORT
    db_name: "$PGVECTOR_DB_NAME"
    user_name: "$PGVECTOR_USER_NAME"
    password: "$PGVECTOR_PASSWORD"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D1M
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT1M_DIR"
    custom_dataset_size: 1000000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift1mCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    m: $HNSW_M
    ef_construction: $HNSW_EF_CONSTRUCTION
    ef_search: $MILVUS_EF_SEARCH
    drop_old: true
    load: true
YML
    fi

    if [[ "$WANT_10M" == "true" ]]; then
      cat >> "$OUT_YML" <<YML

  - db_label: pgvector_sift10m
    host: "$PGVECTOR_HOST"
    port: $PGVECTOR_PORT
    db_name: "$PGVECTOR_DB_NAME"
    user_name: "$PGVECTOR_USER_NAME"
    password: "$PGVECTOR_PASSWORD"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D10M
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT10M_DIR"
    custom_dataset_size: 10000000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift10mCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    m: $HNSW_M
    ef_construction: $HNSW_EF_CONSTRUCTION
    ef_search: $MILVUS_EF_SEARCH
    drop_old: true
    load: true
YML
    fi
  fi

  if wantSection "elasticsearch"; then
    cat >> "$OUT_YML" <<YML

tencentelasticsearch:
YML
    if [[ "$WANT_100K" == "true" ]]; then
      cat >> "$OUT_YML" <<YML
  - db_label: elasticsearch_sift100k
    scheme: "$ELASTICSEARCH_SCHEME"
    host: "$ELASTICSEARCH_HOST"
    port: $ELASTICSEARCH_PORT
    user: "$ELASTICSEARCH_USER"
    password: "$ELASTICSEARCH_PASSWORD"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D100K
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT100K_DIR"
    custom_dataset_size: 100000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift100kCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    m: $HNSW_M
    ef_construction: $HNSW_EF_CONSTRUCTION
    num_candidates: $ELASTIC_NUM_CANDIDATES
    drop_old: true
    load: true
YML
    fi

    if [[ "$WANT_1M" == "true" ]]; then
      cat >> "$OUT_YML" <<YML

  - db_label: elasticsearch_sift1m
    scheme: "$ELASTICSEARCH_SCHEME"
    host: "$ELASTICSEARCH_HOST"
    port: $ELASTICSEARCH_PORT
    user: "$ELASTICSEARCH_USER"
    password: "$ELASTICSEARCH_PASSWORD"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D1M
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT1M_DIR"
    custom_dataset_size: 1000000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift1mCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    m: $HNSW_M
    ef_construction: $HNSW_EF_CONSTRUCTION
    num_candidates: $ELASTIC_NUM_CANDIDATES
    drop_old: true
    load: true
YML
    fi

    if [[ "$WANT_10M" == "true" ]]; then
      cat >> "$OUT_YML" <<YML

  - db_label: elasticsearch_sift10m
    scheme: "$ELASTICSEARCH_SCHEME"
    host: "$ELASTICSEARCH_HOST"
    port: $ELASTICSEARCH_PORT
    user: "$ELASTICSEARCH_USER"
    password: "$ELASTICSEARCH_PASSWORD"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D10M
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT10M_DIR"
    custom_dataset_size: 10000000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift10mCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    m: $HNSW_M
    ef_construction: $HNSW_EF_CONSTRUCTION
    num_candidates: $ELASTIC_NUM_CANDIDATES
    drop_old: true
    load: true
YML
    fi
  fi

  if wantSection "elasticcloudhnsw"; then
    cat >> "$OUT_YML" <<YML

elasticcloudhnsw:
YML
    if [[ "$WANT_100K" == "true" ]]; then
      cat >> "$OUT_YML" <<YML
  - db_label: elastic_sift100k
    cloud_id: "$ELASTIC_CLOUD_ID"
    password: "$ELASTIC_PASSWORD"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D100K
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT100K_DIR"
    custom_dataset_size: 100000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift100kCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    m: $HNSW_M
    ef_construction: $HNSW_EF_CONSTRUCTION
    num_candidates: $ELASTIC_NUM_CANDIDATES
    number_of_shards: $ELASTIC_NUMBER_OF_SHARDS
    number_of_replicas: $ELASTIC_NUMBER_OF_REPLICAS
    drop_old: true
    load: true
YML
    fi

    if [[ "$WANT_1M" == "true" ]]; then
      cat >> "$OUT_YML" <<YML

  - db_label: elastic_sift1m
    cloud_id: "$ELASTIC_CLOUD_ID"
    password: "$ELASTIC_PASSWORD"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D1M
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT1M_DIR"
    custom_dataset_size: 1000000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift1mCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    m: $HNSW_M
    ef_construction: $HNSW_EF_CONSTRUCTION
    num_candidates: $ELASTIC_NUM_CANDIDATES
    number_of_shards: $ELASTIC_NUMBER_OF_SHARDS
    number_of_replicas: $ELASTIC_NUMBER_OF_REPLICAS
    drop_old: true
    load: true
YML
    fi

    if [[ "$WANT_10M" == "true" ]]; then
      cat >> "$OUT_YML" <<YML

  - db_label: elastic_sift10m
    cloud_id: "$ELASTIC_CLOUD_ID"
    password: "$ELASTIC_PASSWORD"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D10M
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT10M_DIR"
    custom_dataset_size: 10000000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift10mCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    m: $HNSW_M
    ef_construction: $HNSW_EF_CONSTRUCTION
    num_candidates: $ELASTIC_NUM_CANDIDATES
    number_of_shards: $ELASTIC_NUMBER_OF_SHARDS
    number_of_replicas: $ELASTIC_NUMBER_OF_REPLICAS
    drop_old: true
    load: true
YML
    fi
  fi

  if wantSection "pinecone"; then
    cat >> "$OUT_YML" <<YML

pinecone:
YML
    if [[ "$WANT_100K" == "true" ]]; then
      cat >> "$OUT_YML" <<YML
  - db_label: pinecone_sift100k
    api_key: "$PINECONE_API_KEY"
    index_name: "$PINECONE_INDEX_NAME"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D100K
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT100K_DIR"
    custom_dataset_size: 100000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift100kCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    drop_old: true
    load: true
YML
    fi

    if [[ "$WANT_1M" == "true" ]]; then
      cat >> "$OUT_YML" <<YML

  - db_label: pinecone_sift1m
    api_key: "$PINECONE_API_KEY"
    index_name: "$PINECONE_INDEX_NAME"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D1M
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT1M_DIR"
    custom_dataset_size: 1000000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift1mCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    drop_old: true
    load: true
YML
    fi

    if [[ "$WANT_10M" == "true" ]]; then
      cat >> "$OUT_YML" <<YML

  - db_label: pinecone_sift10m
    api_key: "$PINECONE_API_KEY"
    index_name: "$PINECONE_INDEX_NAME"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D10M
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT10M_DIR"
    custom_dataset_size: 10000000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift10mCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    drop_old: true
    load: true
YML
    fi
  fi

  if wantSection "lsmvec"; then
    cat >> "$OUT_YML" <<YML

lsmvec:
YML
    if [[ "$WANT_100K" == "true" ]]; then
      cat >> "$OUT_YML" <<YML
  - db_label: lsmvec_sift100k
    db_root: "$LSMVEC_DB_ROOT_100K"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D100K
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT100K_DIR"
    custom_dataset_size: 100000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift100kCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    drop_old: true
    load: true
YML
    fi

    if [[ "$WANT_1M" == "true" ]]; then
      cat >> "$OUT_YML" <<YML

  - db_label: lsmvec_sift1m
    db_root: "$LSMVEC_DB_ROOT_1M"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D1M
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT1M_DIR"
    custom_dataset_size: 1000000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift1mCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    drop_old: true
    load: true
YML
    fi

    if [[ "$WANT_10M" == "true" ]]; then
      cat >> "$OUT_YML" <<YML

  - db_label: lsmvec_sift10m
    db_root: "$LSMVEC_DB_ROOT_10M"
    case_type: PerformanceCustomDataset
    custom_case_name: PerfSIFT128D10M
    custom_dataset_name: SIFT
    custom_dataset_dir: "$SIFT10M_DIR"
    custom_dataset_size: 10000000
    custom_dataset_dim: 128
    custom_dataset_metric_type: L2
    custom_dataset_file_count: $sift10mCount
    custom_dataset_use_shuffled: false
    custom_dataset_with_gt: true
    k: $K
    num_concurrency: $NUM_CONCURRENCY
    drop_old: true
    load: true
YML
    fi
  fi

  echo "Batch config written to: $OUT_YML"
}

listTargetContainers() {
  local projectsCsv="$1"
  local nameFiltersCsv="$2"

  {
    IFS=',' read -r -a projects <<< "$projectsCsv"
    for p in "${projects[@]}"; do
      p="$(echo "$p" | xargs)"
      [[ -z "$p" ]] && continue
      docker ps \
        --filter "label=com.docker.compose.project=$p" \
        --format '{{.ID}}\t{{.Names}}\t{{.Label "com.docker.compose.project"}}' || true
    done

    IFS=',' read -r -a names <<< "$nameFiltersCsv"
    for n in "${names[@]}"; do
      n="$(echo "$n" | xargs)"
      [[ -z "$n" ]] && continue
      docker ps \
        --filter "name=$n" \
        --format '{{.ID}}\t{{.Names}}\t{{.Label "com.docker.compose.project"}}' || true
    done
  } | awk 'NF>=2 {print $1 "\t" $2 "\t" $3}' | sort -u
}

DOCKER_SAMPLER_PID=""
dockerSamplerLoop() {
  local outFile="$1"
  local intervalSec="$2"
  local projectsCsv="$3"
  local nameFiltersCsv="$4"

  while true; do
    local ts containerList ids stats
    local used total avail serverMemUsed

    ts="$(date -u '+%Y-%m-%dT%H:%M:%S.%3NZ')"
    IFS=$'\t' read -r used total avail < <(getServerMemSummaryMiB)
    serverMemUsed="$used"

    containerList="$(listTargetContainers "$projectsCsv" "$nameFiltersCsv" || true)"
    if [[ -z "$containerList" ]]; then
      sleep "$intervalSec"
      continue
    fi

    ids="$(echo "$containerList" | awk '{print $1}' | tr '\n' ' ')"
    if [[ -z "$ids" ]]; then
      sleep "$intervalSec"
      continue
    fi

    stats="$(docker stats --no-stream \
      --format '{{.Container}}\t{{.MemUsage}}\t{{.MemPerc}}\t{{.CPUPerc}}' \
      $ids 2>/dev/null || true)"

    if [[ -n "$stats" ]]; then
      awk -v ts="$ts" -v serverMemUsed="$serverMemUsed" -F'\t' '
        NR==FNR {name[$1]=$2; proj[$1]=$3; next}
        {
          id=$1
          if (id in name) {
            print ts "\t" name[id] "\t" proj[id] "\t" $2 "\t" $3 "\t" $4 "\t" serverMemUsed
          }
        }
      ' <(echo "$containerList") <(echo "$stats") >> "$outFile"
    fi

    sleep "$intervalSec"
  done
}

startDockerMemSampler() {
  local outFile="$1"
  local intervalSec="$2"
  local projectsCsv="$3"
  local nameFiltersCsv="$4"

  mkdir -p "$(dirname "$outFile")"
  echo -e "ts_utc\tcontainer_name\tcompose_project\tmem_usage\tmem_perc\tcpu_perc\tserver_mem_used_mib" > "$outFile"

  dockerSamplerLoop "$outFile" "$intervalSec" "$projectsCsv" "$nameFiltersCsv" >/dev/null 2>&1 &
  DOCKER_SAMPLER_PID=$!
}

stopDockerMemSampler() {
  local pid="${1:-}"
  if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
    kill "$pid" 2>/dev/null || true
    wait "$pid" 2>/dev/null || true
  fi
}

getProcessTreePids() {
  local rootPid="$1"
  if [[ -z "$rootPid" ]] || ! kill -0 "$rootPid" 2>/dev/null; then
    return 0
  fi

  declare -A visited
  local -a queue all
  queue=("$rootPid")
  all=("$rootPid")
  visited["$rootPid"]=1

  while [[ ${#queue[@]} -gt 0 ]]; do
    local pid="${queue[0]}"
    queue=("${queue[@]:1}")

    local children
    children="$(ps --no-headers -o pid= --ppid "$pid" 2>/dev/null | awk '{print $1}' || true)"
    [[ -z "$children" ]] && continue

    local c
    while read -r c; do
      [[ -z "$c" ]] && continue
      if [[ -z "${visited[$c]+x}" ]]; then
        visited["$c"]=1
        all+=("$c")
        queue+=("$c")
      fi
    done <<< "$children"
  done

  printf "%s\n" "${all[@]}"
}

HOST_SAMPLER_PID=""
hostSamplerLoop() {
  local outFile="$1"
  local intervalSec="$2"
  local rootPid="$3"

  while kill -0 "$rootPid" 2>/dev/null; do
    local ts rssSumKib rssSumMib num
    local used total avail serverMemUsed
    local -a pids

    ts="$(date -u '+%Y-%m-%dT%H:%M:%S.%3NZ')"
    IFS=$'\t' read -r used total avail < <(getServerMemSummaryMiB)
    serverMemUsed="$used"

    mapfile -t pids < <(getProcessTreePids "$rootPid" || true)
    num="${#pids[@]}"

    if [[ "$num" -eq 0 ]]; then
      echo -e "${ts}\t${rootPid}\t0\t0\t0\t${serverMemUsed}" >> "$outFile"
      sleep "$intervalSec"
      continue
    fi

    rssSumKib="$(
      ps -o rss= -p "$(IFS=','; echo "${pids[*]}")" 2>/dev/null \
        | awk '{s+=$1} END{printf "%.0f", s+0}'
    )"
    rssSumMib="$(awk -v x="$rssSumKib" 'BEGIN{printf "%.2f", x/1024.0}')"

    echo -e "${ts}\t${rootPid}\t${num}\t${rssSumKib}\t${rssSumMib}\t${serverMemUsed}" >> "$outFile"
    sleep "$intervalSec"
  done
}

startHostMemSampler() {
  local outFile="$1"
  local intervalSec="$2"
  local rootPid="$3"

  mkdir -p "$(dirname "$outFile")"
  echo -e "ts_utc\troot_pid\tnum_procs\trss_kib\trss_mib\tserver_mem_used_mib" > "$outFile"

  hostSamplerLoop "$outFile" "$intervalSec" "$rootPid" >/dev/null 2>&1 &
  HOST_SAMPLER_PID=$!
}

stopHostMemSampler() {
  local pid="${1:-}"
  if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
    kill "$pid" 2>/dev/null || true
    wait "$pid" 2>/dev/null || true
  fi
}

usage() {
  cat >&2 <<EOF
Usage: $0 [TARGET] [DATASETS]
TARGET:
  all|baselines|lsmvec|milvushnsw|qdrantlocal|weaviate|pgvectorhnsw|elasticsearch|elasticcloudhnsw|pinecone
Aliases:
  milvus -> milvushnsw
  qdrant -> qdrantlocal
  pgvector -> pgvectorhnsw
  elastic|elasticsearch -> elasticsearch
  elasticcloud -> elasticcloudhnsw
DATASETS:
  100k,1m,10m or all
Examples:
  $0 all 100k,1m,10m
  $0 weaviate 10m
Env:
  SIFT_DATASETS=100k,1m
EOF
}

main() {
  requireCmd awk
  requireCmd ps
  requireCmd tee
  requireCmd vectordbbench

  if [[ "$ENABLE_DOCKER_MEM_SAMPLING" == "true" ]]; then
    requireCmd docker
  fi

  if wantSection "elasticsearch"; then
    requireCmd curl
    ensureElasticsearchReachable
  fi

  mkdir -p "$ROOT/bench_runs" "$DOCKER_STATS_OUT_DIR" "$HOST_STATS_OUT_DIR"

  if [[ -z "$TARGET" ]]; then
    usage
    exit 1
  fi

  [[ "$WANT_100K" == "true" ]] && verifyDatasetDir "$SIFT100K_DIR"
  [[ "$WANT_1M" == "true" ]] && verifyDatasetDir "$SIFT1M_DIR"
  [[ "$WANT_10M" == "true" ]] && verifyDatasetDir "$SIFT10M_DIR"

  writeYaml

  for i in $(seq 1 "$REPEATS"); do
    echo "Run $i / $REPEATS (TARGET=$TARGET_RAW -> $TARGET, DATASETS=$DATASETS_RAW -> $DATASETS_TAG)"

    local runTs outLog dockerStatsFile hostStatsFile
    local dockerSamplerPid hostSamplerPid benchPid exitCode

    runTs="$(date -u '+%Y%m%dT%H%M%SZ')"
    outLog="$ROOT/bench_runs/run_${runTs}_target_${TARGET}_ds_${DATASETS_TAG}.log"
    dockerStatsFile="$DOCKER_STATS_OUT_DIR/docker_mem_${runTs}_target_${TARGET}_ds_${DATASETS_TAG}.tsv"
    hostStatsFile="$HOST_STATS_OUT_DIR/host_mem_${runTs}_target_${TARGET}_ds_${DATASETS_TAG}.tsv"

    dockerSamplerPid=""
    hostSamplerPid=""

    if [[ "$ENABLE_DOCKER_MEM_SAMPLING" == "true" ]]; then
      printSystemMemBefore "docker mem sampler"
      echo "Docker mem sampling enabled, interval=${DOCKER_STATS_INTERVAL_SEC}s"
      echo "Projects: $DOCKER_STATS_PROJECTS"
      echo "Name filters: $DOCKER_STATS_NAME_FILTERS"
      echo "Docker stats file: $dockerStatsFile"
      startDockerMemSampler "$dockerStatsFile" "$DOCKER_STATS_INTERVAL_SEC" "$DOCKER_STATS_PROJECTS" "$DOCKER_STATS_NAME_FILTERS"
      dockerSamplerPid="$DOCKER_SAMPLER_PID"
    fi

    printSystemMemBefore "vectordbbench batchcli"
    echo "Run log: $outLog"

    stdbuf -oL -eL vectordbbench batchcli --batch-config-file "$OUT_YML" > >(tee "$outLog") 2>&1 &
    benchPid=$!

    if [[ "$ENABLE_HOST_MEM_SAMPLING" == "true" ]]; then
      printSystemMemBefore "host mem sampler (process tree of pid ${benchPid})"
      echo "Host mem sampling enabled, interval=${HOST_STATS_INTERVAL_SEC}s"
      echo "Host stats file: $hostStatsFile"
      echo "Host root pid: $benchPid"
      startHostMemSampler "$hostStatsFile" "$HOST_STATS_INTERVAL_SEC" "$benchPid"
      hostSamplerPid="$HOST_SAMPLER_PID"
    fi

    wait "$benchPid"
    exitCode=$?

    stopHostMemSampler "$hostSamplerPid"
    stopDockerMemSampler "$dockerSamplerPid"

    [[ "$ENABLE_DOCKER_MEM_SAMPLING" == "true" ]] && echo "Docker stats: $dockerStatsFile"
    [[ "$ENABLE_HOST_MEM_SAMPLING" == "true" ]] && echo "Host stats: $hostStatsFile"

    if [[ $exitCode -ne 0 ]]; then
      echo "ERROR: vectordbbench exited with code $exitCode" >&2
      exit $exitCode
    fi
  done
}

main "$@"
